### ISSUE TITLE
Beatsage and Beatsage Downloader

### ISSUE THREAD

**Issue by zan5hin** [Arimodu/BeatZip#1]
Hi, I found your app because I'm trying to generate beatsage songs and sync to BMBF on my Quest.

Beatsage: https://uploadvr.com/beat-sage-ai-custom-beat-saber/

A nice person made an unofficial desktop app: https://www.reddit.com/r/beatsage/comments/gm9gpo/beat_sage_downloader_unofficial/

however, when complete, the files are not zipped: https://prnt.sc/ttmprt and that's where I thought your app would help.

I'm doing something wrong, as tried copying those finished songs into a new folder c:\bmbf and then trying to have your app zip them correctly, but it's giving me an error:  https://prnt.sc/ttmqfk

Any assistance would be fantastic for the community.

Cheers

**Comment by Arimodu** [comment]
Hey there,
thanks for noting this. The app has the path to standard beatsaber songs
directory hardcoded in the path generation. That means that it
automatically adds "\beat saber_data\CustomSongs\" to the path.

You can either wait for me to release a patch for this, or you can put the
songs to subfolders to simulate the beat saber PC installation song path.
In your case it would look something like this: "C:\bmbf\Beat
Saber_data\CustomSongs\<your song folder>


Cheers
Arimodu

**Comment by Arimodu** [comment]
Hey there, its me again.
I am notifying you that I have added BeatSage mode to the newest release. 
Download the release and pass the "-BeatSageMode" to the application to use it.

Cheers
Arimodu

**Comment by Arimodu** [comment]
Marking this issue closed.

**Comment by zan5hin** [comment]
Hi, Thanks so much for pushing out the update.  I tried to get it working without success.

On my main PC where I previously installed Beatzip, I overwrote the .exe and and cmd ran beatzip -BeatSageMode, response was "Beat Sage mode is an unknown argument" and then threw up the history from the old .exe with the unhandled exception error about not finding the path.

So I tried on my windows tablet, copied the new .exe and some songs on a portable drive, and ran beatzip -BeatSageMode.

This time, it asked for my install directory, I put D:\bmbf and again it gave me the unhandled exception error.

This history file thing, I don't understand.  Now after it fails once, when I try to run it again, it doesn't ask me for the installation folder, if I try to just re-run beatzip.exe it says "History file detected and enabled!" throws up the unhandled exception and falls over.

**Comment by Arimodu** [comment]
Hi,
that seems weird. I'll look into it.
Also the history is just to make the system easier to use. It is set up so
you don't have to enter the path again and also be able to delete the older
archives to save up space.
You can disable history by passing -disableHistory argument. I will be
adding shorter argument tables.

I'll probably try to push the update today but nothing is guaranteed yet.

Cheers
Arimodu

**Comment by Arimodu** [comment]
[BeatZip.zip](https://github.com/Arimodu/BeatZip/files/5026796/BeatZip.zip)

**Comment by Arimodu** [comment]
Ok try with the executable above. I have re-done the argument detection. It would seem that it did not register the string input.
Please let me know if it works or if it does not. 

Cheers
Arimodu

**Comment by Arimodu** [comment]
Alright, pushing the bugfix now. There were more bugs than I had expected. It works on my machine but I didn't have the time to do my standard VM test.

You can download the latest release. I have, among other things, added a help page and a shortened argument table. The old arguments work just fine.

Please let me know if it finally resolved your issue.

Cheers
Arimodu

**Comment by zan5hin** [comment]
Sorry, still having problems  :D



Then I just created a new folder c:\too and copied one song (too original) to see if just doing one folder with song files would make a difference:



It said successful, but it failed.  All that happened was that it created a new folder in downloads which was called "old" and was empty.



Here are some of the BeatSage songs I just convereted, if that helps: https://1drv.ms/u/s!Ah5Pa1SGd3kCh8Ihajx31-UpuWCfMg?e=jd7hYv 

Cheers
Adam

**Comment by Arimodu** [comment]
Hey there,
So just making sure I understand. You took a folder which has just the song
files (expertplus.dat,etc) in it and tried to zip that?
If that's the case then you have to put the song FOLDERS in a folder and
set it to be the source. The app zips from the contents of a folder and
uses the folders name for the .zip
If there are no folders in a directory it will appear that it finished
since 0 does equal 0

It should look like this:
\foo\song1\expertplus.dat
        \song2\expertplus.dat

And the source would be:
\foo

Also as the source there should be the full path i.e.
C:\users\foo\desktop\foo

In the scenario above you would get two zip files named song1 and song2.

There can be any number of songs. In the \foo folder, beatzip will zip them
one-by-one.

Cheers
Arimodu

**Comment by zan5hin** [comment]
OK great news! It's working for me :D Thanks!



However I think there is still a bug, if you are trying to use a subfolder of the source path as the destination, see below:



I will comment on the Beatsage reddit post about your app soon :D

Thanks heaps, can start converting lots more songs very easily now.
On 6/08/2020 4:31:41 PM, Arimodu <notifications@github.com> wrote:
Hey there,
So just making sure I understand. You took a folder which has just the song
files (expertplus.dat,etc) in it and tried to zip that?
If that's the case then you have to put the song FOLDERS in a folder and
set it to be the source. The app zips from the contents of a folder and
uses the folders name for the .zip
If there are no folders in a directory it will appear that it finished
since 0 does equal 0

It should look like this:
\foo\song1\expertplus.dat
\song2\expertplus.dat

And the source would be:
\foo

Also as the source there should be the full path i.e.
C:\users\foo\desktop\foo

In the scenario above you would get two zip files named song1 and song2.

There can be any number of songs. In the \foo folder, beatzip will zip them
one-by-one.

Cheers
Arimodu

**Comment by Arimodu** [comment]
Hey there,
I'll mark the issue as closed. If you could tell me the details of the bug you mentioned above.
Also thanks for the post on Reddit.  I really appreciate it.

Cheers
Arimodu
